const tg = window.Telegram?.WebApp;
tg?.ready(); tg?.expand();
const initData = tg?.initData || "";
const $ = (id) => document.getElementById(id);
const headers = () => ({ Authorization: `tma ${initData}`, "content-type": "application/json" });
const ago = (ms) => { if(!ms) return "—"; const s=Math.max(0,Math.round((Date.now()-ms)/1000)); return s<60?`${s} с`:s<3600?`${Math.round(s/60)} хв`:`${Math.round(s/3600)} год`; };
function stateLabel(p){ const s=p.state; if(s.control.paused) return ["Пауза","warn"]; const st=s.runtime.status||"unknown"; if(["working","assistant"].includes(st)) return ["Працює",""]; if(st.includes("error")||st.includes("failed")) return [st,"bad"]; return [st,"warn"]; }
async function api(path, options={}){ const r=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})}}); const j=await r.json(); if(!r.ok) throw new Error(j.error||`HTTP ${r.status}`); return j; }
function card(p){ const [label,kind]=stateLabel(p); const paused=p.state.control.paused; const excerpt=p.state.runtime.latestAssistantExcerpt||"Ще немає checkpoint від активної вкладки."; return `<article class="card ${paused?'paused':''}"><div class="row"><div><div class="title">${p.name}</div><div class="state"><i class="dot ${kind}"></i>${label}</div></div><a href="${p.chatUrl}">Відкрити чат ↗</a></div><div class="meta"><div>Останній heartbeat<b>${ago(p.state.runtime.lastSeenAt)}</b></div><div>Останній прогрес<b>${ago(p.state.runtime.lastProgressAt)}</b></div><div>Plan anchor<b>${p.planVersion||'v1'}</b></div><div>Watchdog<b>${p.watchdog?.alerted?'⚠ alert':'OK'}</b></div></div><div class="checkpoint">${excerpt.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}</div><div class="actions"><button data-id="${p.id}" data-action="${paused?'resume':'pause'}" class="${paused?'primary':''}">${paused?'▶ Відновити':'Ⅱ Пауза'}</button><button data-id="${p.id}" data-action="restart">↻ Вкладка</button><button data-id="${p.id}" data-action="rollover">＋ Новий чат</button></div></article>`; }
async function load(){ try{ const data=await api('./api/status'); $('summary').textContent=`${data.projects.length} проєкти • ${new Date(data.generatedAt).toLocaleTimeString()}`; $('projects').innerHTML=data.projects.map(card).join(''); $('message').textContent=''; }catch(e){ $('message').textContent=`Помилка: ${e.message}`; } }
$('projects').addEventListener('click',async e=>{ const b=e.target.closest('button[data-action]'); if(!b)return; b.disabled=true; try{ await api(`./api/projects/${b.dataset.id}/action`,{method:'POST',body:JSON.stringify({action:b.dataset.action})}); tg?.HapticFeedback?.impactOccurred('medium'); await load(); }catch(err){$('message').textContent=`Помилка: ${err.message}`;}finally{b.disabled=false;} });
$('refresh').onclick=load;
$('restartService').onclick=async()=>{ if(!confirm('Перезапустити весь Autopilot supervisor?'))return; try{await api('./api/service/restart',{method:'POST',body:'{}'});$('message').textContent='Restart запущено…';}catch(e){$('message').textContent=e.message;} };
load(); setInterval(load,15000);
